name: Scheduler
on:
  schedule:
    - cron: '*/1 * * * *'  # every 5 minutes
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
